# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 10:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 10, 25, 19, 255047, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
